2020-10-27 07:41:57,719 INFO https://datos.cdmx.gob.mx/explore/dataset/fotocivicas/download/?format=csv&timezone=America/Mexico_City&lang=es&use_labels_for_header=true&csv_separator=%2C
2020-10-27 07:41:58,587 INFO data/adip/fotocivicas/fotocivicas.csv
2020-10-27 07:41:58,596 INFO https://datos.cdmx.gob.mx/explore/dataset/diagnostico-sobre-la-ciudad-en-el-mundo/download/?format=csv&timezone=America/Mexico_City&lang=es&use_labels_for_header=true&csv_separator=%2C
2020-10-27 07:41:59,150 INFO data/adip/diagnostico-sobre-la-ciudad-en-el-mundo/diagnostico-sobre-la-ciudad-en-el-mundo.csv
2020-10-27 07:41:59,154 INFO https://datos.cdmx.gob.mx/explore/dataset/incidentes-viales-c5/download/?format=csv&timezone=America/Mexico_City&lang=es&use_labels_for_header=true&csv_separator=%2C
2020-10-27 07:55:34,061 INFO data/adip/incidentes-viales-c5/incidentes-viales-c5.csv
2020-10-27 07:55:39,053 INFO https://datos.cdmx.gob.mx/explore/dataset/mapa_ingresos_parquimetros/download/?format=csv&timezone=America/Mexico_City&lang=es&use_labels_for_header=true&csv_separator=%2C
2020-10-27 07:55:41,096 INFO data/adip/mapa_ingresos_parquimetros/mapa_ingresos_parquimetros.csv
2020-10-27 07:55:41,102 INFO https://datos.cdmx.gob.mx/explore/dataset/contador-ciclistas/download/?format=csv&timezone=America/Mexico_City&lang=es&use_labels_for_header=true&csv_separator=%2C
2020-10-27 07:55:42,497 INFO data/adip/contador-ciclistas/contador-ciclistas.csv
2020-10-27 07:55:42,501 INFO https://datos.cdmx.gob.mx/explore/dataset/carpetas-de-investigacion-pgj-de-la-ciudad-de-mexico/download/?format=csv&timezone=America/Mexico_City&lang=es&use_labels_for_header=true&csv_separator=%2C
2020-10-27 08:06:42,992 INFO data/adip/carpetas-de-investigacion-pgj-de-la-ciudad-de-mexico/carpetas-de-investigacion-pgj-de-la-ciudad-de-mexico.csv
2020-10-27 08:06:44,816 INFO https://datos.cdmx.gob.mx/explore/dataset/victimas-en-carpetas-de-investigacion-pgj/download/?format=csv&timezone=America/Mexico_City&lang=es&use_labels_for_header=true&csv_separator=%2C
2020-10-27 08:10:59,180 INFO data/adip/victimas-en-carpetas-de-investigacion-pgj/victimas-en-carpetas-de-investigacion-pgj.csv
2020-10-27 08:10:59,537 INFO https://datos.cdmx.gob.mx/explore/dataset/prueba-parquimetros/download/?format=csv&timezone=America/Mexico_City&lang=es&use_labels_for_header=true&csv_separator=%2C
2020-10-27 08:11:02,022 INFO data/adip/prueba-parquimetros/prueba-parquimetros.csv
2020-10-27 08:11:02,027 INFO https://datos.cdmx.gob.mx/explore/dataset/hechos-de-transito-reportados-por-ssc-base-comparativa/download/?format=csv&timezone=America/Mexico_City&lang=es&use_labels_for_header=true&csv_separator=%2C
2020-10-27 08:11:30,477 INFO data/adip/hechos-de-transito-reportados-por-ssc-base-comparativa/hechos-de-transito-reportados-por-ssc-base-comparativa.csv
2020-10-27 08:11:30,509 INFO https://datos.cdmx.gob.mx/explore/dataset/hechos-de-transito-registrados-por-la-ssc-serie-para-comparaciones-interanuales-/download/?format=csv&timezone=America/Mexico_City&lang=es&use_labels_for_header=true&csv_separator=%2C
2020-10-27 08:11:30,803 ERROR 
------------------------------
ERROR
Traceback (most recent call last):
  File "download_files.py", line 30, in download
    filedata = urllib2.urlopen(url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found
2020-10-27 08:11:30,804 INFO https://datos.cdmx.gob.mx/explore/dataset/gtfs-general-transit-feed-specifications-actualizado-de-la-ciudad-de-mexico/download/?format=csv&timezone=America/Mexico_City&lang=es&use_labels_for_header=true&csv_separator=%2C
2020-10-27 08:11:31,832 INFO data/adip/gtfs-general-transit-feed-specifications-actualizado-de-la-ciudad-de-mexico/gtfs-general-transit-feed-specifications-actualizado-de-la-ciudad-de-mexico.csv
2020-10-27 08:11:31,837 INFO https://datos.cdmx.gob.mx/explore/dataset/vialidades-de-la-ciudad-de-mexico/download/?format=csv&timezone=America/Mexico_City&lang=es&use_labels_for_header=true&csv_separator=%2C
2020-10-27 08:11:32,726 INFO data/adip/vialidades-de-la-ciudad-de-mexico/vialidades-de-la-ciudad-de-mexico.csv
2020-10-27 08:11:32,730 INFO https://datos.cdmx.gob.mx/explore/dataset/ciclovias/download/?format=csv&timezone=America/Mexico_City&lang=es&use_labels_for_header=true&csv_separator=%2C
2020-10-27 08:11:33,765 INFO data/adip/ciclovias/ciclovias.csv
2020-10-27 08:11:33,769 INFO https://datos.cdmx.gob.mx/explore/dataset/estaciones-de-ecobici/download/?format=csv&timezone=America/Mexico_City&lang=es&use_labels_for_header=true&csv_separator=%2C
2020-10-27 08:11:34,459 INFO data/adip/estaciones-de-ecobici/estaciones-de-ecobici.csv
2020-10-27 08:11:34,463 INFO https://datos.cdmx.gob.mx/explore/dataset/base-covid-sinave/download/?format=csv&timezone=America/Mexico_City&lang=es&use_labels_for_header=true&csv_separator=%2C
2020-10-27 08:20:28,955 INFO data/adip/base-covid-sinave/base-covid-sinave.csv
2020-10-27 08:20:30,517 INFO http://187.191.75.115/gobmx/salud/datos_abiertos/datos_abiertos_covid19.zip
2020-10-27 08:22:40,785 ERROR 
------------------------------
ERROR
Traceback (most recent call last):
  File "download_files.py", line 30, in download
    filedata = urllib2.urlopen(url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 110] Connection timed out>
2020-10-27 08:22:40,785 INFO https://publicacionexterna.azurewebsites.net/publicaciones/places
2020-10-27 08:22:41,731 INFO data/cre/places/places.xml
2020-10-27 08:22:41,742 INFO https://publicacionexterna.azurewebsites.net/publicaciones/prices
2020-10-27 08:22:42,388 INFO data/cre/prices/prices.xml
